name: Vercel Deploy

on:
  push:
    branches:
      - main
    paths:
      - packages/dashboard/**
      - packages/shared/**

jobs:
  deploy:
    name: Deploy dashboard
    runs-on: ubuntu-latest
    concurrency: vercel-deploy
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: packages/dashboard
      - run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: packages/dashboard
      - run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: packages/dashboard
